service: games-organizer-bot

frameworkVersion: "3"

package:
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1

functions:
  echo:
    handler: handler.echobot
    events:
      - http:
          path: /bot
          method: post

plugins:
  - serverless-dotenv-plugin