org: antoniokov
app: games-organizer
service: games-organizer-bot

package:
  excludeDevDependencies: true

useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    BOT_TOKEN: ${env:BOT_TOKEN}
    FIBERY_HOST: ${env:FIBERY_HOST}
    FIBERY_SYNC_TOKEN: ${env:FIBERY_SYNC_TOKEN}
    FIBERY_UI_TOKEN: ${env:FIBERY_UI_TOKEN}
    FIBERY_APP: ${env:FIBERY_APP, 'Organizer'}

functions:
  ui:
    handler: ui.handler
    events:
      - http:
          path: /bot
          method: post
  sync:
    handler: sync.handler
    events:
      - http:
          path: /sync-game
          method: post