service: games-organizer-bot

frameworkVersion: "3"

package:
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}

custom:
  dotenv:
    path: ./.env.${self:provider.stage}

functions:
  ui:
    handler: ui.handler
    events:
      - http:
          path: /bot
          method: post
  sync:
    handler: sync.handler
    events:
      - http:
          path: /sync-game
          method: post
plugins:
  - serverless-dotenv-plugin